# Use official Node.js LTS image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --production

# Copy app source code
COPY . .

# Build TypeScript
RUN npm run build

# Expose port
EXPOSE 3001

# Start the backend server with PM2 in cluster mode
RUN npm install pm2 -g
CMD ["pm2-runtime", "dist/infrastructure/api/server.js", "--instances", "max", "--no-daemon"]
